# Weather Station List
This lab is cleaning file for Data Model

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
df = pd.read_csv("../../data/raw/Yashaswi/climate_station_list.csv")

In [66]:
df.head(3)

,Station Name,Province,Latitude,Longitude,Elevation,Climate ID,WMO Identifier,TC Identifier,First Year,Last Year,HLY First Year,HLY Last Year,DLY First Year,DLY Last Year,MLY First Year,MLY Last Year
0,(AE) BOW SUMMIT,ALBERTA,51.70,-116.47,2080.0,3050PPF,NaN,NaN,1998,2007,NaN,NaN,1998.0,2007.0,1998.0,2007.0
1,100 MILE HOUSE,BRITISH COLUMBIA,51.65,-121.27,929.6,1095790,NaN,NaN,1957,1959,NaN,NaN,1957.0,1959.0,1957.0,1959.0
2,100 MILE HOUSE,BRITISH COLUMBIA,51.65,-121.30,1059.2,1165791,NaN,NaN,1970,1999,NaN,NaN,1970.0,1999.0,1970.0,1999.0

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8611 entries, 0 to 8610
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Station Name    8611 non-null   str
 1   Province        8611 non-null   str
 2   Latitude        8611 non-null   float64
 3   Longitude       8611 non-null   float64
 4   Elevation       8492 non-null   float64
 5   Climate ID      8611 non-null   str
 6   WMO Identifier  1120 non-null   float64
 7   TC Identifier   1630 non-null   str
 8   First Year      8611 non-null   int64
 9   Last Year       8611 non-null   int64
 10  HLY First Year  1861 non-null   float64
 11  HLY Last Year   1861 non-null   float64
 12  DLY First Year  8516 non-null   float64
 13  DLY Last Year   8516 non-null   float64
 14  MLY First Year  7659 non-null   float64
 15  MLY Last Year   7659 non-null   float64
dtypes: float64(10), int64(2), str(4)
memory usage: 1.1 MB

In [68]:
df.shape
df.columns

Index(['Station Name', 'Province', 'Latitude', 'Longitude', 'Elevation',
       'Climate ID', 'WMO Identifier', 'TC Identifier', 'First Year',
       'Last Year', 'HLY First Year', 'HLY Last Year', 'DLY First Year',
       'DLY Last Year', 'MLY First Year', 'MLY Last Year'],
      dtype='str')

In [69]:
df = df.drop(
    columns=[
        'HLY First Year',
        'HLY Last Year',
        'DLY First Year',
        'DLY Last Year',
        'MLY First Year',
        'MLY Last Year',
        'WMO Identifier',
        'TC Identifier',
        'Elevation',
    ]
)

In [70]:
df.head(3)
df['Province'].value_counts()

Province
BRITISH COLUMBIA             1762
ONTARIO                      1571
ALBERTA                      1469
QUEBEC                       1049
SASKATCHEWAN                  728
MANITOBA                      580
NEWFOUNDLAND AND LABRADOR     326
NOVA SCOTIA                   307
NEW BRUNSWICK                 229
NUNAVUT                       210
NORTHWEST TERRITORIES         176
YUKON                         149
PRINCE EDWARD ISLAND           55
Name: count, dtype: int64

In [71]:

atlantic_provinces = [
    'NEWFOUNDLAND AND LABRADOR',
    'NOVA SCOTIA',
    'NEW BRUNSWICK',
    'PRINCE EDWARD ISLAND'
]

df_atlantic = df[df['Province'].isin(atlantic_provinces)]

In [72]:
df_atlantic.head()

,Station Name,Province,Latitude,Longitude,Climate ID,First Year,Last Year
9,26 MILE DEPOT,NEWFOUNDLAND AND LABRADOR,48.42,-57.07,8403990,1962,1962
11,AALDERSVILLE,NOVA SCOTIA,44.83,-64.51,8204020,2021,2026
22,ABERCROMBIE POINT,NOVA SCOTIA,45.65,-62.72,8200015,1973,1978
32,ACADIA FOREST EXP ST,NEW BRUNSWICK,45.99,-66.36,8100100,1955,2010
39,ACADIEVILLE,NEW BRUNSWICK,46.73,-65.28,8100105,1980,1995

In [73]:
df_atlantic.shape

(917, 7)

In [74]:
df_atlantic = df_atlantic[df_atlantic['Last Year'].isin([2025, 2026])]

In [75]:
df_atlantic.shape

(137, 7)

In [76]:
df_atlantic.head()

,Station Name,Province,Latitude,Longitude,Climate ID,First Year,Last Year
11,AALDERSVILLE,NOVA SCOTIA,44.83,-64.51,8204020,2021,2026
209,ARGENTIA (AUT),NEWFOUNDLAND AND LABRADOR,47.31,-54.00,8400104,1987,2026
234,AROOSTOOK,NEW BRUNSWICK,46.71,-67.72,8100300,1929,2025
329,BACCARO PT,NOVA SCOTIA,43.45,-65.47,8200255,2007,2026
336,BADGER (AUT),NEWFOUNDLAND AND LABRADOR,48.97,-56.07,8400301,1973,2026

In [77]:
df_atlantic['First Year'].drop_duplicates().sort_values()

1182    1920
234     1929
1688    1933
2844    1941
2949    1942
6688    1944
4117    1954
4760    1957
8284    1959
7169    1961
869     1969
1001    1972
336     1973
2658    1976
5734    1979
447     1982
3903    1984
209     1987
6448    1989
513     1992
448     1993
2871    1994
3670    1996
5223    1998
4002    1999
2633    2000
4463    2001
4316    2002
1346    2003
532     2004
2680    2005
753     2006
329     2007
6691    2008
7157    2009
2634    2010
1458    2011
1350    2012
1998    2013
6435    2014
1263    2015
460     2016
4275    2017
1400    2018
3028    2019
3071    2020
11      2021
2694    2022
1457    2023
Name: First Year, dtype: int64

In [78]:
df_atlantic = df_atlantic[df_atlantic['First Year'] > 1992]

In [79]:
df_atlantic.shape

(112, 7)

In [80]:
df_atlantic.info()

<class 'pandas.DataFrame'>
Index: 112 entries, 11 to 8563
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Station Name  112 non-null    str
 1   Province      112 non-null    str
 2   Latitude      112 non-null    float64
 3   Longitude     112 non-null    float64
 4   Climate ID    112 non-null    str
 5   First Year    112 non-null    int64
 6   Last Year     112 non-null    int64
dtypes: float64(2), int64(2), str(3)
memory usage: 7.0 KB

In [82]:
df_atlantic.head(10)

,Station Name,Province,Latitude,Longitude,Climate ID,First Year,Last Year
11,AALDERSVILLE,NOVA SCOTIA,44.83,-64.51,8204020,2021,2026
329,BACCARO PT,NOVA SCOTIA,43.45,-65.47,8200255,2007,2026
448,BAS CARAQUET,NEW BRUNSWICK,47.80,-64.83,8100467,1993,2026
460,BATHURST A,NEW BRUNSWICK,47.63,-65.74,8100506,2016,2026
532,BEDFORD BASIN,NOVA SCOTIA,44.71,-63.63,8200573,2004,2026
533,BEDFORD RANGE,NOVA SCOTIA,44.75,-63.66,8200574,2004,2026
590,BERRY HILL,NEWFOUNDLAND AND LABRADOR,49.62,-57.92,8400506,2021,2026
753,BONAVISTA,NEWFOUNDLAND AND LABRADOR,48.67,-53.11,8400601,2006,2026
963,BURGEO NL,NEWFOUNDLAND AND LABRADOR,47.62,-57.62,8400801,2006,2026
1215,CARIBOU POINT (AUT),NOVA SCOTIA,45.77,-62.68,8200774,1993,2026

In [84]:
df_atlantic.to_csv("Stationlist_clean.csv", index=False)

In [86]:
df_clean = pd.read_csv("./Stationlist_clean.csv")

In [88]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Station Name  112 non-null    str
 1   Province      112 non-null    str
 2   Latitude      112 non-null    float64
 3   Longitude     112 non-null    float64
 4   Climate ID    112 non-null    str
 5   First Year    112 non-null    int64
 6   Last Year     112 non-null    int64
dtypes: float64(2), int64(2), str(3)
memory usage: 6.3 KB